language: clojure
lein: lein2
jdk:
      - openjdk7
      - openjdk6
deploy:
  provider: heroku
  api_key: e9fb3332-5e26-4300-ba1c-77fd2a6f435e
  app:
    master: ask-staging
    production: ask-production